### ISSUE TITLE
Drop down is truncated

### ISSUE THREAD

**Issue by rick-rheo** [fcapano/Edit-This-Cookie#208] opened 2018-05-02 18:08 UTC
This happens about 95% of the time.  Chrome 65 & 66 on MacOS, multiple machines.

![image](https://user-images.githubusercontent.com/26754458/39540942-14945242-4df9-11e8-9767-7abc0f5460f5.png)

**Comment by n10ty** [comment] 2018-05-03 13:49
+1

**Comment by fcapano** [comment] 2018-05-03 13:52
Hi,
can you confirm which version of the extension you are running?

**Comment by n10ty** [comment] 2018-05-03 13:55
Hi. Version 1.4.5. 
Chrome Version 65.0.3325.181 (Official Build) (64-bit)
MacOs High Sierra 10.13.4

**Comment by fcapano** [comment] 2018-05-03 14:03
Ok, then this is likely to be a duplicate of #203 .
That fix has been pushed in version 1.4.6, which is being gradually rolled out. In the next couple of days that version will be completely rolled out and hopefully this issue won't appear again.
I'm closing this issue now, if after the 1.4.6 update you still experience this problem feel free to comment on issue #203

**Closed by fcapano** 2018-05-03 14:03 UTC
